### ISSUE TITLE
Any chance this could be Boost-licensed?

### ISSUE THREAD

**Issue by vinniefalco** [backtrace-labs/umash#1]
The MIT license is not as permissive as the Boost license, and I would like to incorporate this into my upcoming JSON library: https://github.com/CPPAlliance/json

**Comment by pkhuong** [comment]
We're still reviewing the licensing options: we like the uniformity of MIT (or BSD, sometimes) for all open source backtrace projects.

In the meantime, I feel like I must point out that the current C implementation of UMASH isn't particularly portable: it only builds on gcc-compatible compilers, and doesn't include fallback code for platforms without PCLMUL. These issues could all be fixed with some coding, but that hasn't happened yet.

**Comment by pkhuong** [comment]
Yeah, we have to use MIT.
